### ISSUE TITLE
KeyError: 'CUDA_PATH'

### ISSUE THREAD

**Issue by WYVERN2742** [WebxCT/WebCT#98]
On systems where the CUDA SDK does not already exist, distributed .exe versions of WebCT crash on startup with a `KeyError: 'CUDA_PATH'`

This is due to TIGRE not using the bundled cuda sdk, but instead using the system's: https://github.com/CERN/TIGRE/issues/579

```bash
2024-11-21 11:16:33,520 [INFO] root: Welcome to WebCT 0.1.3
Traceback (most recent call last):
  File "app.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webct\__init__.py", line 223, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webct\blueprints\app\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webct\blueprints\app\routes.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tigre\__init__.py", line 18, in <module>
  File "os.py", line 680, in __getitem__
KeyError: 'CUDA_PATH'
```

**Comment by WYVERN2742** [comment]
A potential fix has been uploaded with https://github.com/CERN/TIGRE/commit/9975efe194cec338a92aa112ae8f20aa9007fdbd, but will have to check by compiling tigre from source

**Comment by WYVERN2742** [comment]
Can confirm the TIGRE fix has worked, however as I'm experiencing issues in building TIGRE from source, the fix (deleting / commenting out the section in `tigre.__init__.py`) will need to be applied manually before building distributles
